# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='number')),
            ],
        ),
    ]
