# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrbookapp', '0002_auto_20170826_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='number'),
        ),
    ]
